### ISSUE TITLE
Migrations error

### ISSUE THREAD

**Issue by rajabishek** [bbashy/LaraBin#2]
<img width="978" alt="error" src="https://cloud.githubusercontent.com/assets/6145125/11677509/b0254280-9e64-11e5-82fa-73417e8006f4.png">
On running php artisan after composer install it is giving this error. Not allowing to run the migrations at all.

**Comment by Kryptonit3** [comment]
you may need to run the migrations. try first `php artisan migrate`. there are no install instructions, I just assumed anyone using a package such as this would know to run the migration. make sure you have created the database and user/pass and they have proper permissions to the database. then make sure your `.env` file has the proper database credentials.
